### ISSUE TITLE
Upload Curriculum Manual

### ISSUE THREAD

**Issue by neiljohari** [Syosset/syosset#103]
There is some issue with uploading the curriculum manual (most likely the insane size of the file).

[CURRICULUM MANUAL 2018.pdf](https://github.com/Syosset/syosset/files/1657679/CURRICULUM.MANUAL.2018.pdf)

We could just host it elsewhere, but I think we need to make sure our upload system is solid.

**Comment by kailan** [comment]
https://syosseths.com/static/curriculum_manual_2018.pdf

**Comment by neiljohari** [comment]
escalated
