### ISSUE TITLE
Add school year relevant information

### ISSUE THREAD

**Issue by neiljohari** [Syosset/syosset#13]
Some ideas:
- Classroom model (each course will have multiple classrooms teaching it per year, with a single teacher and a room number)
- User pages (teachers will be able to edit their bio. the classes they teach should show up. their extra help hours should be listable)

**Comment by JinxuanCang** [comment]
We probably need to construct a drag and drop online website designer for teachers.

**Comment by neiljohari** [comment]
Turns out this isn't going to happen because we have 0 data, and the school also has 0 data. We've added schedules for teachers though, hopefully that will take care of it all.
