### ISSUE TITLE
Chat button obstructing the buttons in editing pages

### ISSUE THREAD

**Issue by JinxuanCang** [Syosset/syosset#131]
The lower right red box invoking the chat box is problematic. It obstructs the buttons for the editing pages: e.g. promotion and announcement. Also, set the chat button's z-index higher until not under the text area.
![image](https://user-images.githubusercontent.com/30204954/45260750-1fe39700-b3bd-11e8-9fe7-18e42296ff21.png)
![image](https://user-images.githubusercontent.com/30204954/45260765-97192b00-b3bd-11e8-8066-fee0d29159fb.png)

**Comment by kailan** [comment]
Closed in #136. (Chat is disabled for now)
