### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by neiljohari** [Syosset/syosset#15]
Ability to escalate up to super admin, to ban users from signing in temporarily, etc. Should go hand in hand with teacher/student pages.

**Comment by JinxuanCang** [comment]
I think you should contact the district Google accounts administrator and request the permission and privileges to administrate and manipulate our Google Accounts, as well. If this issue is resolved, please close the issue.

**Comment by kailan** [comment]
@JinxuanCang I can’t see any benefit to us having access to those kind of administrative permissions for student accounts, care to elaborate?

**Comment by neiljohari** [comment]
I agree with @kailan. Even if we were given permission for something like this, it would be really risky to have a student run club (Web Dev) have this kind of power over personal accounts.

However, we have reached out to Mr. Gessner for a complete student and staff email + schedule list. That’s enough information for us to improve the site’s functionality.
