### ISSUE TITLE
Add in depth tracking system

### ISSUE THREAD

**Issue by neiljohari** [Syosset/syosset#3]
Will be used in Announcements

**Comment by neiljohari** [comment]
Roll our own or use Impressionist gem? @kailan 

https://github.com/charlotte-ruby/impressionist
vs
https://github.com/OvercastNetwork/OCN/blob/f706a16409782e3b44b5333c61f88c0b116a4fd9/app/models/viewable.rb

**Comment by kailan** [comment]
@neiljohari We could probably just roll our own, it's not a huge feature.

**Comment by neiljohari** [comment]
Along with views tracking, we should track changes to models and attribute them to users (important because inappropriate content needs to be attributable to specific users).

**Comment by neiljohari** [comment]
Audit log with https://github.com/mongoid/mongoid-history

**Comment by neiljohari** [comment]
Auditing added. 

Closing as I don't think logging view count is necessary. It would be a pain to track for users who aren't signed in, and having a signed-in count is somewhat useless.
