### ISSUE TITLE
Trimming Dispensable Frameworks and Maximize Native CSS and JavaScript Usage

### ISSUE THREAD

**Issue by JinxuanCang** [Syosset/syosset#69]
Syosseths.com is running out of RAM. Please trim off dispensable framework and utilize native CSS and JavaScript more sufficiently. Using to many frameworks is not easy for future maintaince, otherwise, please document as many framework usage as possible.

**Comment by kailan** [comment]
This is a non-issue, as CSS and JavaScript assets do not consume significant resources on the app server.
