### ISSUE TITLE
Awry Teachers' Email Addresses and Department Teacher List

### ISSUE THREAD

**Issue by JinxuanCang** [Syosset/syosset#85]
Please double check each teacher's email address, some teachers' email addresses are not first initial and last name.
Please revise the Department Teacher List of the English Department. My Algebra 2 teacher is there?

**Comment by neiljohari** [comment]
These lists were generated based off of the previous "Meet the Teachers" lists which were manually typed out.

Could you please look through the department pages and let us know which ones aren't in "first name's first initial + last name" format?

Also, I will check out the problem with the Math teacher being listed there. Are you talking about Ms. Gordon (`sgordon@syosset.k12.ny.us`)?

**Comment by JinxuanCang** [comment]
Yes I am talking about Ms. Gordon. And my English teacher Ms. Goodman has the email address mogoodman@syosset....

**Comment by neiljohari** [comment]
@JinxuanCang The issue with Ms. Goodman has been fixed for the English department.

@kailan The real Monica Goodman already signed in once 4 months ago. I removed the incorrect user we accidentally created from the collaborator group, and added the right one.

Should be fine destroying the incorrect user afaik. As soon as you also confirm, I'll delete.

**Comment by neiljohari** [comment]
Being handled
