### ISSUE TITLE
Markdown editor loads multiple times

### ISSUE THREAD

**Issue by kailan** [Syosset/syosset#92]
Steps to reproduce:
1) Go to https://syosseths.com/users/edit
2) Navigate away
3) Go back to the page

**Comment by kailan** [comment]
Related to this issue – it appears that _all_ text areas become markdown editors.

![screen shot 2018-01-17 at 21 21 55](https://user-images.githubusercontent.com/3542064/35067645-80e0e214-fbcc-11e7-84fc-088511124645.png)

**Comment by neiljohari** [comment]
This issue has become somewhat urgent.

Tuesday I will be in a meeting with the principal to discuss an initiative to try and increase the number of users who are setting up their profiles. We need to have this ironed out before then to prevent confusion.

**Comment by kailan** [comment]
https://github.com/Syosset/syosset/commit/2e5d75b3f7bfbe74bf60fb656ddf918b82bce62f
